"""initial schema

Revision ID: 0c149baba2ad
Revises:
Create Date: 2026-08-08 19:17:22.220806
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = "0c149baba2ad"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("circuit_ref", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("circuit_ref"),
    )
    op.create_table(
        "constructors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("constructor_ref", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("constructor_ref"),
    )
    op.create_table(
        "drivers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("driver_ref", sa.String(length=100), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("forename", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("driver_ref"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year"),
    )
    op.create_table(
        "sessions",
        sa.Column("session_key", sa.Integer(), nullable=False),
        sa.Column("session_name", sa.String(length=100), nullable=True),
        sa.Column("session_type", sa.String(length=50), nullable=True),
        sa.Column("meeting_key", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("date_start", sa.DateTime(), nullable=True),
        sa.Column("date_end", sa.DateTime(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("session_key"),
    )
    op.create_index("ix_sessions_year", "sessions", ["year"], unique=False)
    op.create_table(
        "telemetry_samples",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_key", sa.Integer(), nullable=False),
        sa.Column("driver_number", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("gear", sa.Integer(), nullable=True),
        sa.Column("throttle", sa.Integer(), nullable=True),
        sa.Column("brake", sa.Integer(), nullable=True),
        sa.Column("drs", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_key", "driver_number", "date", name="uq_telem_session_driver_ts"
        ),
    )
    op.create_index("ix_telem_session", "telemetry_samples", ["session_key"], unique=False)
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("circuit_ref", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.String(length=20), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["circuit_ref"],
            ["circuits.circuit_ref"],
        ),
        sa.ForeignKeyConstraint(
            ["season_year"],
            ["seasons.year"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_year", "round", name="uq_race_season_round"),
    )
    op.create_table(
        "lap_times",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("driver_ref", sa.String(length=100), nullable=False),
        sa.Column("lap", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("time_millis", sa.BigInteger(), nullable=True),
        sa.Column("time_str", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_ref"],
            ["drivers.driver_ref"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "driver_ref", "lap", name="uq_lap_race_driver_lap"),
    )
    op.create_index("ix_laps_race_driver", "lap_times", ["race_id", "driver_ref"], unique=False)
    op.create_table(
        "pit_stops",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("driver_ref", sa.String(length=100), nullable=False),
        sa.Column("stop", sa.Integer(), nullable=False),
        sa.Column("lap", sa.Integer(), nullable=False),
        sa.Column("time_of_day", sa.String(length=20), nullable=True),
        sa.Column("duration_millis", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_ref"],
            ["drivers.driver_ref"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "driver_ref", "stop", name="uq_pit_race_driver_stop"),
    )
    op.create_table(
        "race_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("driver_ref", sa.String(length=100), nullable=False),
        sa.Column("constructor_ref", sa.String(length=100), nullable=False),
        sa.Column("grid", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("position_text", sa.String(length=10), nullable=True),
        sa.Column("points", sa.Float(), nullable=True),
        sa.Column("laps", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=True),
        sa.Column("time_millis", sa.BigInteger(), nullable=True),
        sa.Column("fastest_lap_rank", sa.Integer(), nullable=True),
        sa.Column("fastest_lap_time", sa.String(length=20), nullable=True),
        sa.Column("fastest_lap_speed", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["constructor_ref"],
            ["constructors.constructor_ref"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_ref"],
            ["drivers.driver_ref"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "driver_ref", name="uq_result_race_driver"),
    )
    op.create_index("ix_results_race", "race_results", ["race_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_results_race", table_name="race_results")
    op.drop_table("race_results")
    op.drop_table("pit_stops")
    op.drop_index("ix_laps_race_driver", table_name="lap_times")
    op.drop_table("lap_times")
    op.drop_table("races")
    op.drop_index("ix_telem_session", table_name="telemetry_samples")
    op.drop_table("telemetry_samples")
    op.drop_index("ix_sessions_year", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("seasons")
    op.drop_table("drivers")
    op.drop_table("constructors")
    op.drop_table("circuits")
    # ### end Alembic commands ###
